name: DrugShift Bot Scheduled Run

on:
  # التشغيل اليدوي من تبويب Actions في GitHub
  workflow_dispatch:


jobs:
  run-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        # مهم جداً: كل الأوامر ستعمل داخل مجلد Last
        working-directory: Last
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # --- الخطوة الجديدة والأكثر أهمية ---
      # تقوم هذه الخطوة بحفظ ملف الجلسة بعد انتهاء التشغيل واستعادته في بداية التشغيل التالي
      - name: Cache Telethon session file
        uses: actions/cache@v4
        id: telethon-cache
        with:
          # المسار الصحيح للملف بناءً على working-directory
          path: scraper_session.session
          # مفتاح فريد للتخزين. سيتم استعادة آخر نسخة متطابقة
          key: ${{ runner.os }}-telethon-session-v1
          restore-keys: |
            ${{ runner.os }}-telethon-session-v1

      - name: List files for debug (after cache restore)
        run: ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DrugShift Bot
        env:
          # تم الاحتفاظ بجميع متغيرات البيئة الخاصة بك كما هي
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          X_REQUESTED_WITH: ${{ secrets.X_REQUESTED_WITH }}
          REFERER: ${{ secrets.REFERER }}
          REQUEST_TIMEOUT_SECONDS: ${{ secrets.REQUEST_TIMEOUT_SECONDS }}
          MAX_RETRIES: ${{ secrets.MAX_RETRIES }}
          RETRY_DELAY_SECONDS: ${{ secrets.RETRY_DELAY_SECONDS }}
          PAGE_SIZE_LIMIT: ${{ secrets.PAGE_SIZE_LIMIT }}
          MAX_CONCURRENT_REQUESTS: ${{ secrets.MAX_CONCURRENT_REQUESTS }}
          CONNECTOR_LIMIT: ${{ secrets.CONNECTOR_LIMIT }}
          CONNECTOR_LIMIT_PER_HOST: ${{ secrets.CONNECTOR_LIMIT_PER_HOST }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_TABLE: ${{ secrets.SUPABASE_TABLE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
        run: |
          python Connection.py
